---
# file: roles/common/tasks/main.yml

# ntp
- name: be sure ntp is installed
  yum:
    name: ntp
    state: present
  tags: ntp

- name: be sure ntpd is running and enabled
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp

# default packages
- name: be sure default packages are installed
  yum:
    name: ['epel-release', 'wget', 'git', 'zsh', 'emacs-nox', 'vim', 'ansible', 'curl', 'gcc-c++', 'make']
    state: present