---
# file: roles/mariadb/tasks/main.yml
# mariadb
- name: install mariadb
  yum:
    name: mariadb-server
    state: present

- name: enable mariadb service
  systemd:
    name: mariadb
    state: started
    enabled: yes

